"""empty message

Revision ID: ce642cb311c7
Revises: 791cd7d80402
Create Date: 2018-04-29 20:58:15.018523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce642cb311c7'
down_revision = '791cd7d80402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('campus', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDisciplina', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=10), nullable=True),
    sa.Column('nivel', sa.String(length=10), nullable=True),
    sa.Column('turma', sa.String(length=10), nullable=True),
    sa.Column('docente', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=10), nullable=True),
    sa.Column('horario', sa.String(length=1000), nullable=True),
    sa.Column('local', sa.String(length=30), nullable=True),
    sa.Column('matriculados', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='guests_pkey')
    )
    op.drop_table('turmas')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
