"""empty message

Revision ID: bfe49ec25577
Revises: 0ed182aac4ff
Create Date: 2018-04-30 13:34:39.218818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe49ec25577'
down_revision = '0ed182aac4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('campus', sa.String(length=30), nullable=True),
    sa.Column('curso', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idDisciplina', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=True),
    sa.Column('nivel', sa.String(length=10), nullable=True),
    sa.Column('turma', sa.String(length=10), nullable=True),
    sa.Column('docente', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=10), nullable=True),
    sa.Column('horario', sa.String(length=1000), nullable=True),
    sa.Column('local', sa.String(length=30), nullable=True),
    sa.Column('matriculados', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['idDisciplina'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id', 'idDisciplina')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
